### ISSUE TITLE
`property` seems to ignore `:gen` clauses in specs

### ISSUE THREAD

**Issue by neshtea** [active-group/active-quickcheck#6]
# Expectation

If a spec is defined with an explicit generator (via the `:gen`) option, I would expect the `property` macro to generate values using that generator.

# Observation

`property` seems to ignore the `:gen` clause.  Example:

```clojure
(ns example.check
  (:use [active.quickcheck])
  (:require [clojure.spec.alpha :as s]
            [clojure.test :as t]
            [clojure.test.check.generators :as gen]))

(s/def ::nat pos-int?)

(def sure-its-always-4-elems
  "A spec that always generates a list of exactly four distinct positive
  integers."
  (s/spec (s/coll-of ::nat :into [])
          :gen (fn []
                 (gen/list-distinct (s/gen ::nat) {:num-elements 4}))))

;; This works
(s/exercise sure-its-always-4-elems)

;; This doesn't work but instead generates examples with `nil` cases.
(quickcheck
 (property [ks (spec sure-its-always-4-elems)]
           (let [[a b c d] ks]
             (t/is (distinct? a b c d)))))
```

In this example, `exercise` always generates a vector of exactly four distinct numbers.  Quickcheck, on the other hand, also generates lists with `nil` in them:

```
FAIL in () (NO_SOURCE_FILE:23)
expected: (distinct? a b c d)
  actual: (not (distinct? nil nil nil nil))
Falsifiable, after 0 tests:
ks = []
```

I would expect `quickcheck` to respect the provided gen.  Is this a bug or a user-error?

**Comment by cresh** [comment]
It's a bug. Was working when spec that was defined with `s/sdef` to a namespaced keyword, but not when bound to a name, like in your example.

**Comment by neshtea** [comment]
@cresh The test you added seems to show that it works 👍
